### ISSUE TITLE
Second sprint week

### ISSUE THREAD

**Issue by aguinot** [GalSim-developers/GalSim-Euclid-Like#84]
Overarching goals:
1. Get repo in shape for review by EC members in preparation for making it public
2. Tag v0.1 that is for a test run prior to a large-scale run

- [ ] Observation sequence (Axel)
  - [ ] Update file #82 - Axel will address feedback and merge
  - [x] Building script
  - [x] Notebook with plots
- [ ] WCS 
  - [ ] Unit tests (Rachel, Axel) - take inspiration from galsim.roman WCS unit tests
  - [x] Building script #79  (Axel)
- [x] PSF (Federico)
  - [x] Fix normalization #83 
  - [x] Define mag range -> pupil_bin and include saturation  #46  
  - [x] Make it possible to use getPSF() without downloading the entire dataset #91 
- [ ] Background (Axel)
  - [ ] Fix bug that makes spatially varying background #85 - should try to understand, but not a huge impact
- [x] Bandpass (Rachel)
  - [x] Update bandpass #43 
  - [x] Fix/documentation normalization - #87 
  - [x] Red/Blue limit definition (documentation) #80 #87
- [ ] Photometry error (Axel)
  - [ ] Fix current bugs #73 
- [ ] Validation
  - [x] Move current run to Vera (Axel)
  - [ ] Run validation #47 #53  (and other tests) (Andy, Axel)
  - [ ] Look into Q1 release for PSF validation
  - [ ] Define tests #59 (all to discuss on Friday)
  - [ ] Stretch goal: computational resource estimate #58 
- [ ] Repo stuffs
  - [x] Update GalSim dependency #48 (Federico)
  - [x] Update install instructions #63 (Federico)
  - [x] Clean up / prepare public release #81 (Federico, Andy)
  - [ ] Stretch goal: documentation with Sphinx #76 (Federico to set up, then we all work on it)

**Comment by rmandelb** [comment]
The sprint in September was a success, and I'm closing since we have moved on from this.
